Examen2DS39B/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Examen2DS39B.Models;

namespace Examen2DS39B.Controllers
{
    public class ClienteController : Controller
    {
        examen2ds39Entities context = new examen2ds39Entities();
        // GET: Cliente
        public ActionResult Index()
        {
            if (Session["rol"]!=null)
            {
                if (Session["rol"].Equals("administrador"))
                {
                    //cargar transacciones
                    List<cliente> data = context.cliente.ToList();

                    ViewBag.data = data;

                    IList<SelectListItem> roles = new List<SelectListItem>{
                new SelectListItem{Text = "administrador", Value = "administrador"},
                new SelectListItem{Text = "cliente", Value = "cliente"}
                };

                    ViewBag.roles = roles;

                    if (TempData["msj"] != null)
                    {
                        ViewBag.msj = TempData["msj"];
                    }

                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }

                    
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult Index(cliente c)
        {
            if (ModelState.IsValid)
            {
                string accion = Request.Form["boton"].ToString();

                switch (accion)
                {
                    case "Guardar":

                        int existe = (from x in context.cliente where x.cod_cliente == c.cod_cliente && x.nit == c.nit select x.cod_cliente).Count();
                        int codCliente = (from x in context.cliente where x.cod_cliente == c.cod_cliente select x.cod_cliente).Count();
                        int nitCliente = (from x in context.cliente where x.nit == c.nit select x.nit).Count();

                        if (existe > 0)
                        {
                            TempData["msj"] = "existe";
                            return RedirectToAction("Index");
                        }
                        else if (codCliente > 0)
                        {
                            TempData["msj"] = "existe_codigo";
                            return RedirectToAction("Index");
                        }
                        if (nitCliente > 0)
                        {
                            TempData["msj"] = "existe_nit";
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            TempData["msj"] = "Guardado";
                            context.cliente.Add(c);
                            context.SaveChanges();
                        }

                        break;

                    case "Eliminar":

                        context.cliente.Remove(context.cliente.FirstOrDefault(x => x.cod_cliente == c.cod_cliente));
                        context.SaveChanges();
                        TempData["msj"] = "Eliminado";

                        break;

                    case "Modificar":

                        //sacar el registro del context, el que se va a modificar
                        cliente temp = context.cliente.FirstOrDefault(x => x.cod_cliente == c.cod_cliente);
                        //aplicando la modificacion campo por campo
                        temp.nombre_cliente = c.nombre_cliente;
                        temp.nombre_cliente = c.nombre_cliente;
                        temp.nit = c.nit;
                        temp.rol = c.rol;
                        //guardar cambios
                        context.SaveChanges();
                        TempData["msj"] = "Modificado";

                        break;
                }

                return RedirectToAction("Index");
            }
            else
            {
                TempData["msj"] = "Datos";
                return RedirectToAction("Index");
            }
        }

    }
}

Examen2DS39B/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>


                    @{
                        if (Session["rol"] != null)
                        {
                            if (Session["rol"].Equals("administrador"))
                            {
                                <li>@Html.ActionLink("Cuenta", "Index", "Cuenta")</li>
                                <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                            }
                            else if(Session["rol"].Equals("cliente"))
                            {
                                <li>@Html.ActionLink("Transacciones", "Index", "Transacciones")</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Index", "Login")</li>
                        }

                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>